r"""Bregman divergences for the Conditional Generator Matching (CGM) loss.

Generator Matching's gradient identity (Holderrieth et al., 2024,
Proposition 2) requires the per-sample discrepancy ``D(F_t^z, F_t^\theta)``
between the conditional generator target and the network's emission to be a
Bregman divergence

.. math::

   D_\phi(a, b) = \phi(a) - \phi(b) - \langle a - b, \nabla\phi(b)\rangle,

for a strictly-convex ``\phi``. Bregman divergences are linear in their first
argument, which is what makes per-data-point conditional minimisation
equivalent in expectation to the (intractable) marginal one. Any other
discrepancy breaks that equivalence.

This module provides the three classics from the GM literature, each defined on
its proper convex domain ``\Omega``:

* :class:`SquaredL2` on ``\mathbb{R}^d`` — the MSE instance (flow / drift,
  Gaussian diffusion coefficient).
* :class:`KLDivergence` on the probability simplex — jump / CTMC rates.
* :class:`ItakuraSaito` on the positive orthant — variance-/rate-like
  coefficients.

Choosing ``\phi`` to match the target's domain is structural:
applying squared-L2 to a probability-vector target still computes a gradient,
but the GM identity no longer holds (see the Bregman-divergence-loss concept
note).

References
----------
- Holderrieth et al., *Generator Matching*, 2024 (§6, Prop. 2; Eq. 15, 17).
"""

from __future__ import annotations

from dataclasses import dataclass

import torch


def _reduce_event(per_element: torch.Tensor, lead: tuple[int, ...]) -> torch.Tensor:
    """Mean-reduce trailing (event) dimensions to a per-sample scalar.

    Args:
        per_element (torch.Tensor): Per-element divergence with leading shape
            ``lead`` followed by event dimensions.
        lead (tuple[int, ...]): Leading (sample/batch) shape to preserve.

    Returns:
        torch.Tensor: Tensor of shape ``lead``.
    """
    return per_element.reshape(*lead, -1).mean(dim=-1)


class BregmanDivergence:
    r"""Base class for per-sample Bregman divergences ``D_\phi(a, b)``.

    Subclasses implement :meth:`__call__` returning the per-sample divergence
    between ``prediction`` (``b = F_t^\theta``) and ``target``
    (``a = F_t^z``), reduced over the event dimensions to leading shape
    ``lead``.
    """

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        lead: tuple[int, ...],
    ) -> torch.Tensor:
        raise NotImplementedError


@dataclass(frozen=True)
class SquaredL2(BregmanDivergence):
    r"""Squared-``L_2`` (MSE) Bregman divergence on ``\mathbb{R}^d``.

    Generated by ``\phi(x) = \tfrac12\|x\|^2``, giving
    ``D_\phi(a, b) = \tfrac12\|a - b\|^2``. The conventional ``\tfrac12`` only
    rescales the loss (not its minimiser or gradient direction); this
    implementation uses the plain mean squared error, matching nami's
    :func:`~nami.losses._common.per_sample_mse` convention.
    """

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        lead: tuple[int, ...],
    ) -> torch.Tensor:
        return _reduce_event((prediction - target).pow(2), lead)


@dataclass(frozen=True)
class KLDivergence(BregmanDivergence):
    r"""KL / cross-entropy Bregman divergence on the probability simplex.

    Generated by the negative entropy ``\phi(x) = \sum_i x_i \log x_i``, giving
    ``D_\phi(a, b) = \sum_i a_i \log(a_i / b_i)`` over the categorical axis
    ``dim``. ``prediction`` and ``target`` are treated as probability vectors;
    pass already-normalised distributions (e.g. softmax outputs and one-hot or
    soft targets).

    The gradient with respect to ``prediction`` equals that of the cross-entropy
    ``-\sum_i a_i \log b_i`` (the ``a \log a`` term is constant in ``b``), so this
    is the natural objective for jump / CTMC rate matching.

    Args:
        dim (int): Categorical axis along which inputs lie on the simplex.
        eps (float): Floor for logarithms, guarding the simplex corners.
    """

    dim: int = -1
    eps: float = 1e-8

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        lead: tuple[int, ...],
    ) -> torch.Tensor:
        a = target.clamp_min(self.eps)
        b = prediction.clamp_min(self.eps)
        per_class = target * (a.log() - b.log())
        per_element = per_class.sum(dim=self.dim)
        return _reduce_event(per_element, lead)


@dataclass(frozen=True)
class ItakuraSaito(BregmanDivergence):
    r"""Itakura-Saito Bregman divergence on the positive orthant.

    Generated by ``\phi(x) = -\sum_i \log x_i``, giving
    ``D_\phi(a, b) = \sum_i (a_i / b_i - \log(a_i / b_i) - 1)``. Defined for
    strictly-positive ``prediction`` and ``target`` (e.g. a positive diffusion
    or rate coefficient); both are clamped to ``eps`` for stability.

    Args:
        eps (float): Strictly-positive floor applied to both arguments.
    """

    eps: float = 1e-8

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        lead: tuple[int, ...],
    ) -> torch.Tensor:
        a = target.clamp_min(self.eps)
        b = prediction.clamp_min(self.eps)
        ratio = a / b
        per_element = ratio - ratio.log() - 1.0
        return _reduce_event(per_element, lead)
